# Generated by Django 6.0.4 on 2026-07-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleet',
            options={'ordering': ['fleet_name'], 'verbose_name': 'Fleet', 'verbose_name_plural': 'Fleets'},
        ),
        migrations.AlterField(
            model_name='fleet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fleet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='fleet',
            table='fleets',
        ),
    ]
