# Generated by Django 6.0.4 on 2026-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('DRIVING', 'Driving'), ('RESTING', 'Resting')], default='AVAILABLE', max_length=20),
        ),
    ]
