# Generated by Django 6.0.4 on 2026-06-30 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleets', '0001_initial'),
        ('vehicles', '0002_vehicle_fleet_alter_vehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('distance_km', models.FloatField(default=0)),
                ('duration_hr', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('ON_ROUTE', 'On Route'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleets.fleet')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
        ),
    ]
